Produce a valid rack response on interaction post error
The third element of a rack return value should respond to #each.

I was getting an error but seeing:

```
RuntimeError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
  <BODY>
    <H1>Internal Server Error</H1>
    undefined method `each' for #&lt;String:0x007f8e62ae5b58&gt;
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) at
     localhost:3077
    </ADDRESS>
  </BODY>
</HTML>
```

with this change, I now see:

```
RuntimeError: An interaction with same description ("PUT new entry") and
provider state ("an empty content register") but a different request
path, response status and response body has already been used. Please
use a different description or provider state.
```

which is much more helpful :-)

Also added a corresponding unit test